import type { Metadata } from 'next';
import { routing, SupportLocale } from '@imkdw-dev-client/i18n';
import { notFound } from 'next/navigation';
import { getMessages } from 'next-intl/server';

import './globals.css';

import { BrainSidebar, SidebarProvider } from '@imkdw-dev-client/ui';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as SupportLocale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <SidebarProvider>
            <BrainSidebar />
            <main>{children}</main>
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
