name: IMKDW-Dev CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Production Dependencies
        run: pnpm i -P
      - name: Build Project
        run: pnpm build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup pnpm v8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Development Dependencies
        run: pnpm i
      - name: Lint Project
        run: pnpm lint

  alert:
    needs: [build, lint, test, E2E]
    runs-on: ubuntu-latest
    steps:
      - name: Push CI Result on Slack
        uses: 8398a7/action-slack@v3
        with:
          author_name: '[SERVER] IMKDW DEV CI Result'
          status: ${{ job.status }}
          fields: repo,message,author,took
          text: ${{ steps.set_text.outputs.text }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
